//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public int BuildingID { get; set; }
        public string BuildingType { get; set; }
        public Nullable<int> BuildingLevel { get; set; }
        public string BuildingName { get; set; }
        public Nullable<int> X { get; set; }
        public Nullable<int> Y { get; set; }
        public Nullable<int> BuildingCost { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
