//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitiesHaveBuilding
    {
        public int CityID { get; set; }
        public int BuildingID { get; set; }
        public Nullable<int> BuildingValue { get; set; }
    
        public virtual Building Building { get; set; }
        private City City { get; set; }
    }
}
