//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitiesHaveTechnology
    {
        public int CityID { get; set; }
        public int TechnologyID { get; set; }
        public Nullable<int> TechnologyBoolStatus { get; set; }
        public Nullable<int> TechnologyCompletionProgress { get; set; }
        public Nullable<int> TechnologyCompletionGoal { get; set; }
        public Nullable<int> TechnologyType { get; set; }
    
        private City City { get; set; }
        public virtual Technology Technology { get; set; }
    }
}
