//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitiesHavePopulation
    {
        public int PUID { get; set; }
        public Nullable<int> PUModifier { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> RaceID { get; set; }
    
        private City City { get; set; }
        public virtual Race Race { get; set; }
    }
}
