//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersistentSum
    {
        public Nullable<int> Gold { get; set; }
        public Nullable<int> Food { get; set; }
        public Nullable<int> RareResources { get; set; }
        public Nullable<int> UID { get; set; }
        public int ID { get; set; }
    }
}
