//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PopulationTemplate
    {
        public int ID { get; set; }
        public string Race { get; set; }
        public Nullable<int> UtilityBonus { get; set; }
        public Nullable<int> MagicBonus { get; set; }
        public Nullable<int> ScienceBonus { get; set; }
        public Nullable<int> DefenseBonus { get; set; }
        public Nullable<int> Str { get; set; }
        public Nullable<int> Dex { get; set; }
        public Nullable<int> Con { get; set; }
        public Nullable<int> Int { get; set; }
        public Nullable<int> Wis { get; set; }
        public Nullable<int> Char { get; set; }
        public Nullable<int> Health { get; set; }
    }
}
